FROM maven:3.5.2-jdk-8-alpine
COPY . /mokulive
WORKDIR /mokulive/client
RUN mvn package -Dmaven.test.skip=true

FROM registry.docker-cn.com/library/java
COPY --from=0 /mokulive/client/target/*.jar . 
EXPOSE 8000
CMD java -jar -Dapollo.meta=$APOLLO_URL -Denv=$ENV *.jar
