apiVersion: v1
kind: Service
metadata:
  name: mokuliveclient
  labels:
    app: mokuliveclient
spec:
  type: {{ .Values.service.mokuliveclient.type }}
  ports:
    - port: {{ .Values.service.mokuliveclient.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mokuliveclient

---

apiVersion: v1
kind: Service
metadata:
  name: mokulivenacos
  labels:
    app: mokulivenacos
spec:
  type: {{ .Values.service.mokulivenacos.type }}
  ports:
    - port: {{ .Values.service.mokulivenacos.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mokulivenacos

---

apiVersion: v1
kind: Service
metadata:
  name: liveserverdownstream
  labels:
    app: liveserverdownstream
spec:
  type: {{ .Values.service.liveserverdownstream.type }}
  ports:
    - port: {{ .Values.service.liveserverdownstream.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: liveserverdownstream
