version: '3.2'
services:
  viz:
    image: bretfisher/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "30001:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
  live_edge:
    image: alaien/live.moku.live-server-nginx-edge
    ports:
      - 8099:80
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    environment:
      - PULL_URL=config.mokulive.stream

  client:
    image: alaien/live.moku.client
    ports:
      - 80:8000
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 60s
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: on-failure
    environment:
      - APOLLO_URL=http://config.mokulive.stream:8080
      - ENV=dev
    networks:
      - client    

       
networks:
  client:
