apiVersion: 'apps/v1beta2'
kind: Deployment
metadata:
  name: client
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      name: client
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: alaien/live-client-springboot:http-flv
        ports:
        - containerPort: 8000
        env:
        - name: CONFIG_SERVER_URL
          value: "http://live-config.herokuapp.com/"
      - name: mq
        image: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    tier: frontend
spec:
  selector:
    app: client
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000

---

apiVersion: 'apps/v1beta2'
kind: Deployment 
metadata:
  name: edge
  labels:
    tier: backend
    app: edge
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: edge
  template:
    metadata:
      name: edge
      labels:
        tier: backend
        app: edge
    spec:
      containers:
      - name: edge
        image: alaien/live-server-nginx-edge:http-flv
        ports:
        - containerPort: 80
        env:
        - name: PULL_URL
          value: 155.94.71.151

---

apiVersion: 'v1'
kind: Service
metadata:
  name: edge
  labels:
    tier: backend
    app: edge
spec:
  selector:
    app: edge
  type: NodePort 
  ports:
  - port: 8880
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mokulive 
spec:
  rules:
  - host: go.mokulive.stream 
    http:
      paths:
      - backend:
          serviceName: client
          servicePort: 80
  - host: edge.mokulive.stream
    http:
      paths:
      - backend:
          serviceName: edge
          servicePort: 8880
